create table audit_logs (
  id       uuid primary key default gen_random_uuid(),
  actor    text not null,   -- 'system' | 'ai:<model>' | user id
  action   text not null,
  entity   text not null,   -- table/entity name
  entity_id uuid,
  before   jsonb,
  after    jsonb,
  at       timestamptz not null default now()
);
create index on audit_logs (entity, entity_id);

-- Checked before every external (money-moving or messaging) call.
-- `key` is the idempotency key itself, generated by the caller.
create table idempotency_keys (
  key         text primary key,
  action_type text not null,
  used_at     timestamptz not null default now()
);

-- Powers the incrementality claim in §11.
create table experiment_results (
  id           uuid primary key default gen_random_uuid(),
  campaign_id  uuid not null references recovery_campaigns(id),
  holdout_group boolean not null,
  outcome      text not null,   -- recovered | not_recovered
  amount       bigint not null,
  recorded_at  timestamptz not null default now()
);
create index on experiment_results (campaign_id);
